name: auth_button_kit
description: Awesome custamisable buttons that help you to build a beautiful login page in just a few clicks
version: 1.0.0
homepage: https://github.com/LeRomino/AuthButtonKit

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.10.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.leromino.auth_button_kit
        pluginClass: AuthButtonKitPlugin
      ios:
        pluginClass: AuthButtonKitPlugin

  assets:
    - assets/logos/
    - assets/logos/dark/
    - assets/logos/light/